from PySide6.QtWidgets import QWidget, QVBoxLayout, QLabel, QPushButton, QComboBox, QCheckBox, QSpinBox, QFormLayout, QGroupBox, QHBoxLayout
from app.gui.themes import Theme


class SettingsPage(QWidget):
    page_name = 'settings'

    def __init__(self, state=None, parent=None):
        super().__init__(parent)
        self.state = state
        self.setObjectName('page')
        layout = QVBoxLayout(self)
        layout.setSpacing(16)
        layout.setContentsMargins(24, 24, 24, 24)
        header = QLabel('Settings')
        header.setStyleSheet('font-size: 24px; font-weight: bold;')
        layout.addWidget(header)

        appearance = QGroupBox('Appearance')
        form = QFormLayout(appearance)
        theme = QComboBox()
        theme.addItems(['System', 'Light', 'Dark'])
        form.addRow('Theme', theme)
        accent = QComboBox()
        accent.addItems(['Blue', 'Green', 'Purple', 'Orange'])
        form.addRow('Accent', accent)
        density = QComboBox()
        density.addItems(['Compact', 'Comfortable', 'Spacious'])
        form.addRow('Density', density)
        animations = QCheckBox('Animations')
        animations.setChecked(True)
        form.addRow('', animations)
        rounded = QCheckBox('Rounded UI')
        rounded.setChecked(True)
        form.addRow('', rounded)
        layout.addWidget(appearance)

        server = QGroupBox('Server')
        sform = QFormLayout(server)
        host = QComboBox()
        host.addItems(['127.0.0.1', '0.0.0.0'])
        sform.addRow('Default host', host)
        port = QSpinBox()
        port.setRange(1, 65535)
        port.setValue(8080)
        sform.addRow('Default port', port)
        auto_ports = QCheckBox('Automatic ports')
        auto_ports.setChecked(True)
        sform.addRow('', auto_ports)
        health = QSpinBox()
        health.setRange(1, 300)
        health.setValue(10)
        sform.addRow('Health interval (sec)', health)
        recovery = QCheckBox('Crash recovery')
        recovery.setChecked(True)
        sform.addRow('', recovery)
        crash_loop = QCheckBox('Crash-loop protection')
        crash_loop.setChecked(True)
        sform.addRow('', crash_loop)
        layout.addWidget(server)

        tunnel = QGroupBox('Tunnels')
        tform = QFormLayout(tunnel)
        provider = QComboBox()
        provider.addItems(['Cloudflare', 'ngrok', 'LocalTunnel', 'None'])
        tform.addRow('Default provider', provider)
        auto_start = QCheckBox('Auto-start')
        auto_start.setChecked(True)
        tform.addRow('', auto_start)
        reconnect = QCheckBox('Reconnect')
        reconnect.setChecked(True)
        tform.addRow('', reconnect)
        auto_open = QCheckBox('Auto-open URL')
        tform.addRow('', auto_open)
        layout.addWidget(tunnel)
        layout.addStretch()
        save = QPushButton('Save Settings')
        save.setObjectName('primary')
        layout.addWidget(save)
